use ort::session::Session;
use rusqlite::Connection;
use std::path::Path;
use usearch::Index;
use uuid::Uuid;

#[derive(Debug, thiserror::Error)]
pub enum PieceError {
    #[error("Database error: {0}")]
    Db(#[from] rusqlite::Error),
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Collection with ID '{0}' not found in database")]
    CollectionNotFound(String),
    #[error("Piece with ID '{0}' not found in database")]
    PieceNotFound(String),
    #[error("Collection with ID '{0}' is of type '{1}', expected '{2}'")]
    InvalidCollectionType(String, String, String),
    #[error("Collection folder '{0}' does not exist on disk")]
    CollectionFolderMissing(String),
    #[error("Text exceeds character limit of {0} (actual: {1})")]
    CharLimitExceeded(usize, usize),
    #[error("Text exceeds token limit of {0} (actual: {1})")]
    TokenLimitExceeded(usize, usize),
    #[error("Tokenizer error: {0}")]
    Tokenizer(String),
    #[error("Vector index error: {0}")]
    VectorIndex(#[from] crate::vector_index::VectorIndexError),
    #[error("ONNX model error: {0}")]
    Onnx(#[from] ort::Error),
}

#[derive(Debug, serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq)]
pub struct Piece {
    pub id: String,
    pub collection_id: String,
    pub uri: Option<String>,
    pub created_at: String,
    pub is_active: bool,
}

/// Ingests a plain text piece by writing it to disk and registering it in SQLite.
///
/// * `conn` - SQLite database connection.
/// * `vibe_path` - Root path of the Vibe workspace.
/// * `collection_id` - The ID of the collection this piece belongs to.
/// * `content` - The raw markdown or plain text content.
/// * `uri` - Optional source URI (e.g. file path or URL).
/// * `metadata` - List of key-value metadata strings to register for this piece.
pub fn ingest_text_piece(
    conn: &mut Connection,
    vibe_path: &Path,
    collection_id: &str,
    content: &str,
    uri: Option<&str>,
    metadata: &[(&str, &str)],
    session: &mut Session,
    index: &Index,
) -> Result<Piece, PieceError> {
    // 0. Validate fail-fast character and precise token limits
    crate::model::validate_limits(content, None, None)?;

    // 1. Resolve collection from SQLite
    let (folder_path, cat_type): (String, String) = conn
        .query_row(
            "SELECT folder_path, type FROM collections WHERE id = ?;",
            [collection_id],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .map_err(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => {
                PieceError::CollectionNotFound(collection_id.to_string())
            }
            _ => PieceError::Db(e),
        })?;

    // 2. Validate collection type is 'text'
    if cat_type != "text" {
        return Err(PieceError::InvalidCollectionType(
            collection_id.to_string(),
            cat_type,
            "text".to_string(),
        ));
    }

    // 3. Verify collection directory exists
    let collection_dir = vibe_path.join(&folder_path);
    if !collection_dir.exists() || !collection_dir.is_dir() {
        return Err(PieceError::CollectionFolderMissing(folder_path));
    }

    // 4. Generate Piece ID and output file path
    let piece_id = Uuid::new_v4().to_string();
    let file_name = format!("{}.md", piece_id);
    let piece_file_path = collection_dir.join(&file_name);

    // 5. Write plain text content to physical file on disk
    std::fs::write(&piece_file_path, content)?;

    // 6. DB changes + Vector changes inside transaction coordinator
    let mut vector_id_opt = None;
    let mut run_tx_sequence = |conn: &mut Connection,
                               vector_id_opt: &mut Option<u64>|
     -> Result<String, PieceError> {
        let tx = conn.transaction()?;

        // Retrieve current timestamp generated by SQLite strftime
        let created_at: String =
            tx.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%SZ', 'now');", [], |row| {
                row.get(0)
            })?;

        tx.execute(
            "INSERT INTO pieces (id, collection_id, uri, created_at, is_active) VALUES (?, ?, ?, ?, 1);",
            rusqlite::params![&piece_id, collection_id, uri, &created_at],
        )?;

        for &(key, val) in metadata {
            tx.execute(
                "INSERT INTO piece_metadata (piece_id, key, value) VALUES (?, ?, ?);",
                [&piece_id, key, val],
            )?;
        }

        // Get/create vector ID mapping
        let vector_id = crate::vector_index::get_or_create_vector_id(&tx, &piece_id)?;
        *vector_id_opt = Some(vector_id);

        // Generate embedding
        let embedding = crate::model::generate_embedding(session, content)?;

        // Add to memory index
        crate::vector_index::add_vector(index, vector_id, &embedding)?;

        // Save index to disk
        crate::vector_index::save_index(index, vibe_path, &folder_path)?;

        tx.commit()?;
        Ok(created_at)
    };

    match run_tx_sequence(conn, &mut vector_id_opt) {
        Ok(created_at) => Ok(Piece {
            id: piece_id,
            collection_id: collection_id.to_string(),
            uri: uri.map(String::from),
            created_at,
            is_active: true,
        }),
        Err(err) => {
            // Rollback disk file on database write failure
            let _ = std::fs::remove_file(&piece_file_path);

            // Revert memory index
            let usearch_path = vibe_path.join(format!("{}.usearch", folder_path));
            if usearch_path.exists() {
                if let Some(path_str) = usearch_path.to_str() {
                    let _ = index.load(path_str);
                }
            } else if let Some(vid) = vector_id_opt {
                let _ = index.remove(vid);
            }

            Err(err)
        }
    }
}

/// Replaces an existing piece with a new version (tombstoning the old one).
pub fn replace_piece(
    conn: &mut Connection,
    vibe_path: &Path,
    old_piece_id: &str,
    content: &str,
    uri: Option<&str>,
    metadata: &[(&str, &str)],
    session: &mut Session,
    index: &Index,
) -> Result<Piece, PieceError> {
    // 0. Validate fail-fast character and precise token limits
    crate::model::validate_limits(content, None, None)?;

    // 1. Resolve old piece's collection info and verify it exists
    let (collection_id, folder_path): (String, String) = conn
        .query_row(
            "SELECT pieces.collection_id, collections.folder_path 
         FROM pieces 
         JOIN collections ON pieces.collection_id = collections.id 
         WHERE pieces.id = ?;",
            [old_piece_id],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .map_err(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => {
                PieceError::PieceNotFound(old_piece_id.to_string())
            }
            _ => PieceError::Db(e),
        })?;

    // 2. Ensure collection directory exists
    let collection_dir = vibe_path.join(&folder_path);
    if !collection_dir.exists() || !collection_dir.is_dir() {
        return Err(PieceError::CollectionFolderMissing(folder_path));
    }

    // 3. Generate new Piece ID and output file path
    let new_piece_id = Uuid::new_v4().to_string();
    let file_name = format!("{}.md", new_piece_id);
    let piece_file_path = collection_dir.join(&file_name);

    // 4. Write plain text content to physical file on disk
    std::fs::write(&piece_file_path, content)?;

    // 5. DB changes + Vector changes inside transaction
    let mut new_vector_id_opt = None;
    let mut run_tx_sequence = |conn: &mut Connection,
                               new_vector_id_opt: &mut Option<u64>|
     -> Result<String, PieceError> {
        let tx = conn.transaction()?;

        // Retrieve current timestamp
        let created_at: String =
            tx.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%SZ', 'now');", [], |row| {
                row.get(0)
            })?;

        // Retrieve old vector ID for index removal
        let old_vector_id = crate::vector_index::get_or_create_vector_id(&tx, old_piece_id)?;

        // Tombstone old piece
        tx.execute(
            "UPDATE pieces SET is_active = 0 WHERE id = ?;",
            [old_piece_id],
        )?;

        // Insert new piece
        tx.execute(
            "INSERT INTO pieces (id, collection_id, uri, created_at, is_active) VALUES (?, ?, ?, ?, 1);",
            rusqlite::params![&new_piece_id, &collection_id, uri, &created_at],
        )?;

        // Insert history record
        tx.execute(
            "INSERT INTO piece_history (parent_piece_id, child_piece_id, change_type, timestamp) VALUES (?, ?, 'replacement', ?);",
            rusqlite::params![old_piece_id, &new_piece_id, &created_at],
        )?;

        // Insert new metadata
        for &(key, val) in metadata {
            tx.execute(
                "INSERT INTO piece_metadata (piece_id, key, value) VALUES (?, ?, ?);",
                [&new_piece_id, key, val],
            )?;
        }

        // Retrieve new vector ID
        let new_vector_id = crate::vector_index::get_or_create_vector_id(&tx, &new_piece_id)?;
        *new_vector_id_opt = Some(new_vector_id);

        // Update vector index
        index.remove(old_vector_id).map_err(|e| {
            PieceError::VectorIndex(crate::vector_index::VectorIndexError::USearch(format!(
                "{:?}",
                e
            )))
        })?;
        let embedding = crate::model::generate_embedding(session, content)?;
        crate::vector_index::add_vector(index, new_vector_id, &embedding)?;

        // Save index
        crate::vector_index::save_index(index, vibe_path, &folder_path)?;

        tx.commit()?;
        Ok(created_at)
    };

    match run_tx_sequence(conn, &mut new_vector_id_opt) {
        Ok(created_at) => Ok(Piece {
            id: new_piece_id,
            collection_id,
            uri: uri.map(String::from),
            created_at,
            is_active: true,
        }),
        Err(err) => {
            // Rollback disk file
            let _ = std::fs::remove_file(&piece_file_path);

            // Revert memory index
            let usearch_path = vibe_path.join(format!("{}.usearch", folder_path));
            if usearch_path.exists() {
                if let Some(path_str) = usearch_path.to_str() {
                    let _ = index.load(path_str);
                }
            } else if let Some(vid) = new_vector_id_opt {
                let _ = index.remove(vid);
            }

            Err(err)
        }
    }
}

/// Extends an existing piece with a new piece linked via 'extension_of' relation.
pub fn extend_piece(
    conn: &mut Connection,
    vibe_path: &Path,
    parent_piece_id: &str,
    content: &str,
    uri: Option<&str>,
    metadata: &[(&str, &str)],
    session: &mut Session,
    index: &Index,
) -> Result<Piece, PieceError> {
    // 0. Validate fail-fast character and precise token limits
    crate::model::validate_limits(content, None, None)?;

    // 1. Resolve parent piece's collection info and verify it exists
    let (collection_id, folder_path): (String, String) = conn
        .query_row(
            "SELECT pieces.collection_id, collections.folder_path 
         FROM pieces 
         JOIN collections ON pieces.collection_id = collections.id 
         WHERE pieces.id = ?;",
            [parent_piece_id],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .map_err(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => {
                PieceError::PieceNotFound(parent_piece_id.to_string())
            }
            _ => PieceError::Db(e),
        })?;

    // 2. Ensure collection directory exists
    let collection_dir = vibe_path.join(&folder_path);
    if !collection_dir.exists() || !collection_dir.is_dir() {
        return Err(PieceError::CollectionFolderMissing(folder_path));
    }

    // 3. Generate new Piece ID and output file path
    let new_piece_id = Uuid::new_v4().to_string();
    let file_name = format!("{}.md", new_piece_id);
    let piece_file_path = collection_dir.join(&file_name);

    // 4. Write plain text content to physical file on disk
    std::fs::write(&piece_file_path, content)?;

    // 5. DB changes + Vector changes inside transaction
    let mut vector_id_opt = None;
    let mut run_tx_sequence = |conn: &mut Connection,
                               vector_id_opt: &mut Option<u64>|
     -> Result<String, PieceError> {
        let tx = conn.transaction()?;

        // Retrieve current timestamp
        let created_at: String =
            tx.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%SZ', 'now');", [], |row| {
                row.get(0)
            })?;

        // Insert new piece (parent remains active)
        tx.execute(
            "INSERT INTO pieces (id, collection_id, uri, created_at, is_active) VALUES (?, ?, ?, ?, 1);",
            rusqlite::params![&new_piece_id, &collection_id, uri, &created_at],
        )?;

        // Insert relation 'extension_of' from new piece to parent piece
        tx.execute(
            "INSERT INTO relations (source_piece_id, target_piece_id, relation_type, created_at) VALUES (?, ?, 'extension_of', ?);",
            rusqlite::params![&new_piece_id, parent_piece_id, &created_at],
        )?;

        // Insert new metadata
        for &(key, val) in metadata {
            tx.execute(
                "INSERT INTO piece_metadata (piece_id, key, value) VALUES (?, ?, ?);",
                [&new_piece_id, key, val],
            )?;
        }

        // Get/create new vector ID
        let vector_id = crate::vector_index::get_or_create_vector_id(&tx, &new_piece_id)?;
        *vector_id_opt = Some(vector_id);

        // Vectorize and add to index
        let embedding = crate::model::generate_embedding(session, content)?;
        crate::vector_index::add_vector(index, vector_id, &embedding)?;

        // Save index
        crate::vector_index::save_index(index, vibe_path, &folder_path)?;

        tx.commit()?;
        Ok(created_at)
    };

    match run_tx_sequence(conn, &mut vector_id_opt) {
        Ok(created_at) => Ok(Piece {
            id: new_piece_id,
            collection_id,
            uri: uri.map(String::from),
            created_at,
            is_active: true,
        }),
        Err(err) => {
            // Rollback disk file
            let _ = std::fs::remove_file(&piece_file_path);

            // Revert memory index
            let usearch_path = vibe_path.join(format!("{}.usearch", folder_path));
            if usearch_path.exists() {
                if let Some(path_str) = usearch_path.to_str() {
                    let _ = index.load(path_str);
                }
            } else if let Some(vid) = vector_id_opt {
                let _ = index.remove(vid);
            }

            Err(err)
        }
    }
}

/// Tombstones a piece by setting `is_active = 0` and removing its vector from the USearch index.
pub fn tombstone_piece(
    conn: &mut Connection,
    vibe_path: &Path,
    piece_id: &str,
    index: &Index,
) -> Result<(), PieceError> {
    // 1. Resolve collection info from the piece to know its index file name
    let (_collection_id, folder_path): (String, String) = conn
        .query_row(
            "SELECT pieces.collection_id, collections.folder_path 
         FROM pieces 
         JOIN collections ON pieces.collection_id = collections.id 
         WHERE pieces.id = ?;",
            [piece_id],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .map_err(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => PieceError::PieceNotFound(piece_id.to_string()),
            _ => PieceError::Db(e),
        })?;

    // 2. Perform DB update and vector removal within transaction
    let tx = conn.transaction()?;

    // Tombstone in SQLite
    tx.execute("UPDATE pieces SET is_active = 0 WHERE id = ?;", [piece_id])?;

    // Retrieve vector ID mapping
    let vector_id = crate::vector_index::get_or_create_vector_id(&tx, piece_id)?;

    // Remove from index
    index.remove(vector_id).map_err(|e| {
        PieceError::VectorIndex(crate::vector_index::VectorIndexError::USearch(format!(
            "{:?}",
            e
        )))
    })?;

    // Save index
    crate::vector_index::save_index(index, vibe_path, &folder_path)?;

    tx.commit()?;

    Ok(())
}

/// Creates an explicit semantic connection between two pieces in SQLite.
pub fn link_pieces(
    conn: &Connection,
    source_piece_id: &str,
    target_piece_id: &str,
    relation_type: &str,
) -> Result<(), PieceError> {
    // 1. Verify source piece exists
    let source_exists: bool = conn.query_row(
        "SELECT EXISTS(SELECT 1 FROM pieces WHERE id = ?);",
        [source_piece_id],
        |row| row.get(0),
    )?;
    if !source_exists {
        return Err(PieceError::PieceNotFound(source_piece_id.to_string()));
    }

    // 2. Verify target piece exists
    let target_exists: bool = conn.query_row(
        "SELECT EXISTS(SELECT 1 FROM pieces WHERE id = ?);",
        [target_piece_id],
        |row| row.get(0),
    )?;
    if !target_exists {
        return Err(PieceError::PieceNotFound(target_piece_id.to_string()));
    }

    // 3. Get timestamp and insert relation
    let created_at: String =
        conn.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%SZ', 'now');", [], |row| {
            row.get(0)
        })?;

    conn.execute(
        "INSERT OR IGNORE INTO relations (source_piece_id, target_piece_id, relation_type, created_at) VALUES (?, ?, ?, ?);",
        rusqlite::params![source_piece_id, target_piece_id, relation_type, &created_at],
    )?;

    Ok(())
}

/// A relation record returned by get_relations.
#[derive(Debug, serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq)]
pub struct Relation {
    pub source_piece_id: String,
    pub target_piece_id: String,
    pub relation_type: String,
    pub created_at: String,
}

/// Retrieves all relations where the piece is either the source or the target.
pub fn get_relations(conn: &Connection, piece_id: &str) -> Result<Vec<Relation>, PieceError> {
    // Verify piece exists
    let exists: bool = conn.query_row(
        "SELECT EXISTS(SELECT 1 FROM pieces WHERE id = ?);",
        [piece_id],
        |row| row.get(0),
    )?;
    if !exists {
        return Err(PieceError::PieceNotFound(piece_id.to_string()));
    }

    let mut stmt = conn.prepare(
        "SELECT source_piece_id, target_piece_id, relation_type, created_at 
         FROM relations 
         WHERE source_piece_id = ? OR target_piece_id = ? 
         ORDER BY created_at DESC;",
    )?;

    let rows = stmt.query_map([piece_id, piece_id], |row| {
        Ok(Relation {
            source_piece_id: row.get(0)?,
            target_piece_id: row.get(1)?,
            relation_type: row.get(2)?,
            created_at: row.get(3)?,
        })
    })?;

    let mut relations = Vec::new();
    for rel in rows {
        relations.push(rel?);
    }

    Ok(relations)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::collections::create_collection;
    use crate::db::init_db;
    use std::fs;
    use std::path::PathBuf;

    struct TestEnv {
        vibe_root: PathBuf,
        conn: Connection,
        collection_id: String,
        session: ort::session::Session,
        index: usearch::Index,
    }

    impl TestEnv {
        fn new(name: &str) -> Self {
            let temp_dir = std::env::temp_dir();
            let vibe_root = temp_dir.join(format!(
                "vibenote_test_pieces_{}_{}",
                name,
                Uuid::new_v4().simple()
            ));
            fs::create_dir_all(&vibe_root).unwrap();

            let db_path = vibe_root.join("vibe.db");
            let conn = init_db(&db_path).unwrap();

            let cat = create_collection(&conn, &vibe_root, "My Notes", "text", "notes").unwrap();

            let session = crate::model::init_model().expect("Failed to init model in TestEnv");
            let index = crate::vector_index::load_or_create_index(&vibe_root, &cat.folder_path)
                .expect("Failed to load/create vector index in TestEnv");

            TestEnv {
                vibe_root,
                conn,
                collection_id: cat.id,
                session,
                index,
            }
        }
    }

    impl Drop for TestEnv {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.vibe_root);
        }
    }

    #[test]
    fn test_ingest_piece_success() {
        let mut env = TestEnv::new("success");
        let content = "## Hello World\nThis is a local note.";
        let metadata_input = vec![("token_count", "12"), ("content_hash", "hash_abc_123")];

        let piece = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            content,
            Some("file:///doc/1.md"),
            &metadata_input,
            &mut env.session,
            &env.index,
        )
        .unwrap();

        // 1. Verify returned struct
        assert_eq!(piece.collection_id, env.collection_id);
        assert_eq!(piece.uri, Some("file:///doc/1.md".to_string()));
        assert!(piece.is_active);
        assert!(!piece.created_at.is_empty());

        // 2. Verify file exists on disk with correct content
        let expected_file_path = env.vibe_root.join("notes").join(format!("{}.md", piece.id));
        assert!(expected_file_path.is_file());
        let disk_content = fs::read_to_string(&expected_file_path).unwrap();
        assert_eq!(disk_content, content);

        // 3. Verify SQLite values
        let (db_uri, is_active): (Option<String>, i32) = env
            .conn
            .query_row(
                "SELECT uri, is_active FROM pieces WHERE id = ?;",
                [&piece.id],
                |row| Ok((row.get(0)?, row.get(1)?)),
            )
            .unwrap();
        assert_eq!(db_uri, Some("file:///doc/1.md".to_string()));
        assert_eq!(is_active, 1);

        // 4. Verify piece metadata
        let token_count: String = env
            .conn
            .query_row(
                "SELECT value FROM piece_metadata WHERE piece_id = ? AND key = 'token_count';",
                [&piece.id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(token_count, "12");

        let content_hash: String = env
            .conn
            .query_row(
                "SELECT value FROM piece_metadata WHERE piece_id = ? AND key = 'content_hash';",
                [&piece.id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(content_hash, "hash_abc_123");

        // 5. Verify vector was added to index
        assert!(env.index.size() >= 1);
    }

    #[test]
    fn test_collection_not_found() {
        let mut env = TestEnv::new("not_found");
        let err = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            "non-existent-col-id",
            "Content",
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap_err();

        assert!(matches!(err, PieceError::CollectionNotFound(_)));
    }

    #[test]
    fn test_invalid_collection_type() {
        let mut env = TestEnv::new("invalid_type");

        // Create contact collection
        let contact_cat = create_collection(
            &env.conn,
            &env.vibe_root,
            "Contacts",
            "contacts",
            "contacts_folder",
        )
        .unwrap();

        let err = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &contact_cat.id,
            "Content",
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap_err();

        assert!(matches!(err, PieceError::InvalidCollectionType(_, _, _)));
    }

    #[test]
    fn test_file_cleanup_on_db_error() {
        let mut env = TestEnv::new("cleanup");

        // Simulate a db error by inserting duplicate metadata keys (PK violation on piece_id, key)
        let metadata_input = vec![("duplicate_key", "value1"), ("duplicate_key", "value2")];

        // Ensure initially the collection directory is empty
        let notes_dir = env.vibe_root.join("notes");
        let initial_count = fs::read_dir(&notes_dir).unwrap().count();
        assert_eq!(initial_count, 0);

        let err = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            "Temporarily written text.",
            None,
            &metadata_input,
            &mut env.session,
            &env.index,
        )
        .unwrap_err();

        assert!(matches!(err, PieceError::Db(_)));

        // Verify the file was cleaned up from the directory
        let final_count = fs::read_dir(&notes_dir).unwrap().count();
        assert_eq!(final_count, 0);
    }

    #[test]
    fn test_replace_piece_success() {
        let mut env = TestEnv::new("replace_success");
        let initial_content = "Version 1";

        let p1 = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            initial_content,
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap();

        // Perform replacement
        let p2_content = "Version 2 (replaced)";
        let p2 = replace_piece(
            &mut env.conn,
            &env.vibe_root,
            &p1.id,
            p2_content,
            Some("file:///doc/2.md"),
            &[("replaced_by", "p2")],
            &mut env.session,
            &env.index,
        )
        .unwrap();

        // 1. Verify p1 is inactive
        let p1_active: i32 = env
            .conn
            .query_row(
                "SELECT is_active FROM pieces WHERE id = ?;",
                [&p1.id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(p1_active, 0);

        // 2. Verify p2 is active and has correct content
        let p2_active: i32 = env
            .conn
            .query_row(
                "SELECT is_active FROM pieces WHERE id = ?;",
                [&p2.id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(p2_active, 1);

        let p2_file_path = env.vibe_root.join("notes").join(format!("{}.md", p2.id));
        let p2_disk_content = fs::read_to_string(p2_file_path).unwrap();
        assert_eq!(p2_disk_content, p2_content);

        // 3. Verify history record
        let (parent, child, change_type): (String, String, String) = env.conn.query_row(
            "SELECT parent_piece_id, child_piece_id, change_type FROM piece_history WHERE parent_piece_id = ?;",
            [&p1.id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
        ).unwrap();
        assert_eq!(parent, p1.id);
        assert_eq!(child, p2.id);
        assert_eq!(change_type, "replacement");

        // 4. Verify index still has 1 active vector (old removed, new added)
        assert_eq!(env.index.size(), 1);
    }

    #[test]
    fn test_extend_piece_success() {
        let mut env = TestEnv::new("extend_success");
        let initial_content = "Base context";

        let p1 = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            initial_content,
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap();

        // Perform extension
        let ext_content = "Additional detail";
        let p2 = extend_piece(
            &mut env.conn,
            &env.vibe_root,
            &p1.id,
            ext_content,
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap();

        // 1. Verify p1 remains active
        let p1_active: i32 = env
            .conn
            .query_row(
                "SELECT is_active FROM pieces WHERE id = ?;",
                [&p1.id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(p1_active, 1);

        // 2. Verify p2 is active
        let p2_active: i32 = env
            .conn
            .query_row(
                "SELECT is_active FROM pieces WHERE id = ?;",
                [&p2.id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(p2_active, 1);

        // 3. Verify relation
        let (source, target, rel_type): (String, String, String) = env.conn.query_row(
            "SELECT source_piece_id, target_piece_id, relation_type FROM relations WHERE source_piece_id = ?;",
            [&p2.id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
        ).unwrap();
        assert_eq!(source, p2.id);
        assert_eq!(target, p1.id);
        assert_eq!(rel_type, "extension_of");

        // 4. Verify both pieces have vectors in index
        assert_eq!(env.index.size(), 2);
    }

    #[test]
    fn test_versioning_non_existent_piece() {
        let mut env = TestEnv::new("non_existent_piece");

        let err_replace = replace_piece(
            &mut env.conn,
            &env.vibe_root,
            "non-existent-id",
            "Content",
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap_err();
        assert!(matches!(err_replace, PieceError::PieceNotFound(_)));

        let err_extend = extend_piece(
            &mut env.conn,
            &env.vibe_root,
            "non-existent-id",
            "Content",
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap_err();
        assert!(matches!(err_extend, PieceError::PieceNotFound(_)));
    }

    #[test]
    fn test_link_pieces_success_and_idempotency() {
        let mut env = TestEnv::new("link_success");

        let p1 = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            "Doc 1",
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap();
        let p2 = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            "Doc 2",
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap();

        // Perform linking
        link_pieces(&env.conn, &p1.id, &p2.id, "refers_to").unwrap();

        // 1. Verify link exists in relations table
        let (source, target, rel_type): (String, String, String) = env.conn.query_row(
            "SELECT source_piece_id, target_piece_id, relation_type FROM relations WHERE source_piece_id = ? AND target_piece_id = ?;",
            [&p1.id, &p2.id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
        ).unwrap();
        assert_eq!(source, p1.id);
        assert_eq!(target, p2.id);
        assert_eq!(rel_type, "refers_to");

        // 2. Test query helper get_relations
        let rels_p1 = get_relations(&env.conn, &p1.id).unwrap();
        assert_eq!(rels_p1.len(), 1);
        assert_eq!(rels_p1[0].source_piece_id, p1.id);
        assert_eq!(rels_p1[0].target_piece_id, p2.id);
        assert_eq!(rels_p1[0].relation_type, "refers_to");

        let rels_p2 = get_relations(&env.conn, &p2.id).unwrap();
        assert_eq!(rels_p2.len(), 1);
        assert_eq!(rels_p2[0].source_piece_id, p1.id);
        assert_eq!(rels_p2[0].target_piece_id, p2.id);

        // 3. Test idempotency
        link_pieces(&env.conn, &p1.id, &p2.id, "refers_to").unwrap();
        let rels_count: i32 = env.conn.query_row(
            "SELECT COUNT(*) FROM relations WHERE source_piece_id = ? AND target_piece_id = ? AND relation_type = 'refers_to';",
            [&p1.id, &p2.id],
            |row| row.get(0),
        ).unwrap();
        assert_eq!(rels_count, 1);
    }

    #[test]
    fn test_link_pieces_not_found() {
        let mut env = TestEnv::new("link_not_found");

        let p1 = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            "Doc 1",
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap();

        // Source doesn't exist
        let err_src = link_pieces(&env.conn, "non-existent", &p1.id, "refers_to").unwrap_err();
        assert!(matches!(err_src, PieceError::PieceNotFound(_)));

        // Target doesn't exist
        let err_tgt = link_pieces(&env.conn, &p1.id, "non-existent", "refers_to").unwrap_err();
        assert!(matches!(err_tgt, PieceError::PieceNotFound(_)));

        // get_relations on non-existent piece
        let err_query = get_relations(&env.conn, "non-existent").unwrap_err();
        assert!(matches!(err_query, PieceError::PieceNotFound(_)));
    }

    #[test]
    fn test_ingest_limits_validation() {
        let mut env = TestEnv::new("validation_limits");

        // 1. Fail character limit check
        let large_content = "a".repeat(2001);
        let err_char = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            &large_content,
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap_err();
        assert!(matches!(
            err_char,
            PieceError::CharLimitExceeded(2000, 2001)
        ));

        // 2. Fail token limit check
        let mut token_dense_content = String::new();
        for i in 0..600 {
            let c1 = (((i / 26) % 26) + 97) as u8 as char;
            let c2 = ((i % 26) + 97) as u8 as char;
            token_dense_content.push(c1);
            token_dense_content.push(c2);
            token_dense_content.push(' ');
        }
        assert!(token_dense_content.chars().count() < 2000);

        let err_token = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            &token_dense_content,
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap_err();
        assert!(matches!(err_token, PieceError::TokenLimitExceeded(800, _)));
    }

    #[test]
    fn test_tombstone_piece_success() {
        let mut env = TestEnv::new("tombstone");
        let content = "This is a test note for tombstoning.";

        // 1. Ingest piece
        let piece = ingest_text_piece(
            &mut env.conn,
            &env.vibe_root,
            &env.collection_id,
            content,
            None,
            &[],
            &mut env.session,
            &env.index,
        )
        .unwrap();

        assert!(piece.is_active);
        assert_eq!(env.index.size(), 1);

        // 2. Call tombstone_piece
        tombstone_piece(&mut env.conn, &env.vibe_root, &piece.id, &env.index).unwrap();

        // 3. Assert in SQLite: is_active is 0
        let is_active: i32 = env
            .conn
            .query_row(
                "SELECT is_active FROM pieces WHERE id = ?;",
                [&piece.id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(is_active, 0);

        // 4. Assert in index: size is 0
        assert_eq!(env.index.size(), 0);

        // 5. Reload index from disk and assert it has 0 size
        let cat_folder: String = env
            .conn
            .query_row(
                "SELECT folder_path FROM collections WHERE id = ?;",
                [&env.collection_id],
                |row| row.get(0),
            )
            .unwrap();
        let reloaded_index =
            crate::vector_index::load_or_create_index(&env.vibe_root, &cat_folder).unwrap();
        assert_eq!(reloaded_index.size(), 0);
    }
}
